java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/2138-king-court.html -PARAM in-location "'2138 King Court'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/alviso-marina.html -PARAM in-location "'Alviso Marina'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/andrew-molera.html -PARAM in-location "'Andrew Molera'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/arastradero-preserve.html -PARAM in-location "'Arastradero Preserve'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/arcata-marsh.html -PARAM in-location "'Arcata Marsh'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/azelea-state-reserve.html -PARAM in-location "'Azelea State Reserve'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/bend-wastewater-treatment-plant.html -PARAM in-location "'Bend Wastewater Treatment Plant'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/big-sur.html -PARAM in-location "'Big Sur'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/bolinas-lagoon.html -PARAM in-location "'Bolinas Lagoon'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/burney-falls.html -PARAM in-location "'Burney Falls'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/butte-valley-wildlife-area.html -PARAM in-location "'Butte Valley Wildlife Area'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/calero-resevoir.html -PARAM in-location "'Calero Resevoir'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/champaign-county.html -PARAM in-location "'Champaign County'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/charleston-slough.html -PARAM in-location "'Charleston Slough'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/chez-frankel.html -PARAM in-location "'Chez Frankel'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/colusa-nwr.html -PARAM in-location "'Colusa NWR'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/coyote-creek.html -PARAM in-location "'Coyote Creek'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/coyote-hills.html -PARAM in-location "'Coyote Hills'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/coyote-point-marina.html -PARAM in-location "'Coyote Point Marina'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/crown-memorial-state-beach.html -PARAM in-location "'Crown Memorial State Beach'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/don-edwards-center.html -PARAM in-location "'Don Edwards Center'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/drawbridge.html -PARAM in-location "'Drawbridge'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/ed-levin-state-park.html -PARAM in-location "'Ed Levin State Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/elkhorn-slough.html -PARAM in-location "'Elkhorn Slough'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/golden-gate-park.html -PARAM in-location "'Golden Gate Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/hawk-hill.html -PARAM in-location "'Hawk Hill'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/haystack-reservoir.html -PARAM in-location "'Haystack Reservoir'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/humboldt-county.html -PARAM in-location "'Humboldt County'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/lower-klamath-nwr.html -PARAM in-location "'Lower Klamath NWR'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/mcclellan-ranch.html -PARAM in-location "'McClellan Ranch'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/merced-nwr.html -PARAM in-location "'Merced NWR'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/monte-bello-open-space-preserve.html -PARAM in-location "'Monte Bello Open Space Preserve'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/monterey-bay.html -PARAM in-location "'Monterey bay'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/morro-bay.html -PARAM in-location "'Morro Bay'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/moss-landing-state-beach.html -PARAM in-location "'Moss Landing State Beach'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/palo-alto-duck-pond.html -PARAM in-location "'Palo Alto Duck Pond'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/panoche-valley.html -PARAM in-location "'Panoche Valley'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/patricks-point-state-park.html -PARAM in-location "'Patricks Point State Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/pescadero-marsh.html -PARAM in-location "'Pescadero Marsh'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/phoenecian-resort.html -PARAM in-location "'Phoenecian Resort'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/pigeon-point.html -PARAM in-location "'Pigeon Point'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/pikes-peak.html -PARAM in-location "'Pikes Peak'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/pillar-point.html -PARAM in-location "'Pillar Point'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/point-reyes-national-seashore.html -PARAM in-location "'Point Reyes National Seashore'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/prairie-creek-redwoods-state-park.html -PARAM in-location "'Prairie Creek Redwoods State Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/prairie-du-chien.html -PARAM in-location "'Prairie du Chien'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/rancho-san-antonio.html -PARAM in-location "'Rancho San Antonio'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/reactivity.html -PARAM in-location "'Reactivity'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/russian-ridge-open-space-preserve.html -PARAM in-location "'Russian Ridge Open Space Preserve'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/sacramento-nwr.html -PARAM in-location "'Sacramento NWR'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/san-gregorio-state-beach.html -PARAM in-location "'San Gregorio State Beach'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/schollenberger-park.html -PARAM in-location "'Schollenberger Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/stanford-university.html -PARAM in-location "'Stanford University'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/state-and-speckles-pond.html -PARAM in-location "'State and Speckles Pond'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/stevens-creek-county-park.html -PARAM in-location "'Stevens Creek County Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/sunnyvale-baylands.html -PARAM in-location "'Sunnyvale Baylands'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/sunnyvale-water-treatment-plant.html -PARAM in-location "'Sunnyvale Water Treatment Plant'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/trinidad-state-beach.html -PARAM in-location "'Trinidad State Beach'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/tuvelle-state-park.html -PARAM in-location "'Tuvelle State Park'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/university-lutheran-church.html -PARAM in-location "'University Lutheran Church'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/vasona-creek.html -PARAM in-location "'Vasona Creek'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/wellfleet-bay.html -PARAM in-location "'Wellfleet Bay'"
java org.apache.xalan.xslt.Process -IN locations.xml -XSL report-xsl/location-report.xsl -OUT html/woodbridge-ecological-preserve.html -PARAM in-location "'Woodbridge Ecological Preserve'"
